openapi: 3.0.0
info:
  description: Demo YAML Spec File for Testing.
  version: 1.0.0
  title: Demo XML APIs
paths:
  /v1/migration/poc/xml:
    get:
      summary: Demo GET API Flow
      operationId: DemoXMLGETRoute
      description: Demo XML YAML GET API
      responses:
        '200':
          description: Success
  /v1/migration/poc2/xml:
    get:
      summary: Demo GET API Flow
      operationId: DemoXMLGETRoutePOC
      description: Demo XML YAML GET API
      responses:
        '200':
          description: Success
servers:
  - url: http://mocktarget.apigee.net/xml
